object_detection:
  model: 'efficientdet_lite0.tflite'
  cameraID: 0             # 0 for default camera
  frameWidth: 640         # Default 640
  frameHeight: 480        # Default 480
  numThreads: 4           # Default 4
  enableEdgeTPU: False    # Default False

mapping:
  mapSize: 25             # Default 100

control:
  pwm: 5                    # Default 5
  stepTime_turn45: 0.925     # Seconds to turn 45 degrees
  stepTime_forward: 0.43   # Seconds to move forward
